package de.jatan.analysisapplication.Domain.Model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class GithubRepository {
  private String stargazers_count;
  private String pushed_at;
  private String subscription_url;
  private String language;
  private String branches_url;
  private String issue_comment_url;
  private String labels_url;
  private String subscribers_url;
  private String releases_url;
  private String svn_url;
  private String id;
  private String forks;
  private String archive_url;
  private String git_refs_url;
  private String forks_url;
  private String statuses_url;
  private String ssh_url;
  private GithubLicense license;
  private String full_name;
  private String size;
  private String languages_url;
  private String html_url;
  private String collaborators_url;
  private String clone_url;
  private String name;
  private String pulls_url;
  private String default_branch;
  private String hooks_url;
  private String trees_url;
  private String tags_url;
  private String _private;
  private String contributors_url;
  private String has_downloads;
  private String notifications_url;
  private String open_issues_count;
  private String description;
  private String created_at;
  private String watchers;
  private String keys_url;
  private String deployments_url;
  private String has_projects;
  private String archived;
  private String has_wiki;
  private String updated_at;
  private String comments_url;
  private String stargazers_url;
  private String disabled;
  private String git_url;
  private String has_pages;
  private GithubOwner owner;
  private String commits_url;
  private String compare_url;
  private String git_commits_url;
  private String blobs_url;
  private String git_tags_url;
  private String merges_url;
  private String downloads_url;
  private String has_issues;
  private String url;
  private String contents_url;
  private String mirror_url;
  private String milestones_url;
  private String teams_url;
  private String fork;
  private String issues_url;
  private String events_url;
  private String issue_events_url;
  private String assignees_url;
  private String open_issues;
  private String watchers_count;
  private String node_id;
  private String homepage;
  private String forks_count;
}
