version: '3.4'
services:

  jatan-db:
    image: mariadb
    networks:
      - jatan_external
    restart: always
    ports:
      - "6001:3306"
    volumes:
      - jatan_maria_db_database_dir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=jatan
      - MYSQL_PASSWORD=jatan
      - MYSQL_DATABASE=jatan
  jatan-sonarqube:
    image: bitnami/sonarqube:latest
    networks:
      - jatan_internal
    restart: always
    environment:
      - SONARQUBE_DATABASE_USER=sonarqube
      - SONARQUBE_DATABASE_NAME=sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bhkjca12eufas
      - POSTGRESQL_HOST=jatan-sonarqube-db
      - POSTGRESQL_ROOT_USER=sonarqube
    ports:
      - "6009:9000"
      - "6010:9092"
    volumes:
      - jatan_sonarqube_data_dir_conf:/opt/sonarqube/conf
      - jatan_sonarqube_data_dir_data:/opt/sonarqube/data
      - jatan_sonarqube_data_dir_ext:/opt/sonarqube/extensions
      - jatan_sonarqube_data_dir_plugins:/opt/sonarqube/lib/bundled-plugins
      - jatan_sonarqube_bitname:/bitnami
  jatan-sonarqube-db:
    image: postgres
    networks:
      - jatan_internal
    restart: always
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=bhkjca12eufas
      - POSTGRES_DB=sonarqube
    ports:
      - "6011:5432"
    volumes:
      - jatan_sonarqube_data_dir_db:/var/lib/postgresql
      # This needs explicit mapping due to https://gihub.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.te$
      - jatan_sonarqube_data_dir_db_data:/var/lib/postgresql/data
#  jatan-analysis-spring:
#    image: jatan/analysis-application
#    ports:
#      - "6020:8080"
#    restart: always
#    depends_on:
#       - jatan-db
#    networks:
#       - jatan_external
networks:
  jatan_internal:
  jatan_external:

volumes:
  jatan_maria_db_database_dir:
  jatan_sonarqube_data_dir_conf:
  jatan_sonarqube_data_dir_data:
  jatan_sonarqube_data_dir_ext:
  jatan_sonarqube_data_dir_plugins:
  jatan_sonarqube_data_dir_db:
  jatan_sonarqube_data_dir_db_data:
  jatan_sonarqube_bitname:
